version: '3.9'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: inserf
      POSTGRES_PASSWORD: inserf123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inserf_net

volumes:
  postgres_data:

networks:
  inserf_net:
    name: inserf_net
    driver: bridge
